### ISSUE TITLE
Other versions

### ISSUE THREAD

**Issue by Paroryx** [Nielotz/MinecraftConsoleClient#3]
Like at the Minecraft Console Client in c, what abt automatically versions, like the server runs on 1.18 and it goes to 1.18 and joins and you can not move, but you can write commands in the chat.. that would be awesome in python!

**Comment by Nielotz** [comment]
Hi, this project is in a very early stage and supports only 1.12.2 (partially). 
Currently I have no time to develop it (I am not sure if I will ever have, because there are other much more valuable projects to support).

To achieve your goal all versions need to be drafted (a few working packets on each).
